
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

# array[start:end:step]
# row selection
print("-----------ROW SELECTION-----------")

print(array[0:3])
print()
print()
print()
print(array[::2])
print()
print()
print()
print(array[::-1])
print()
print()
print()
print(array[::-2])
print()
print()
print()

print("-----------------------------------")

print("-----------COLUMNS SELECTION-----------")

print(array[:, 0])
print()
print()
print()
print(array[:, 1])
print()
print()
print()
print(array[:, 2])
print()
print()
print()
print(array[:, -1])
print()
print()
print()
print(array[:, 0:3])
print()
print()
print()
print(array[:, 1:])
print()
print()
print()
print(array[:, ::2])
print()
print()
print()
print(array[:, ::-1])
print()
print()
print()
print(array[:, ::-2])
print()
print()
print()

print("-----------------------------------")

print("-----------ROW & COLUMNS SELECTION-----------")

print(array[0:2, 0:2])
print()
print()
print()
print(array[0:2, 2:])
print()
print()
print()
print(array[2:, 0:2])
print()
print()
print()
print(array[2:, 2:])
